// Cached DOM references used across screen modules.
export const elements = {
  tabTitle: document.getElementById("tabTitle"),
  tabSubtitle: document.getElementById("tabSubtitle"),
  statusPill: document.getElementById("statusPill"),
  tunnelList: document.getElementById("tunnelList"),
  logsEl: document.getElementById("logs"),
  tunnelNameInput: document.getElementById("tunnelName"),
  tunnelConfigInput: document.getElementById("tunnelConfig"),
  addPanelTitle: document.getElementById("addPanelTitle"),
  cancelTunnelBtn: document.getElementById("cancelTunnelBtn"),
  saveTunnelBtn: document.getElementById("saveTunnelBtn"),
  autoStart: document.getElementById("autoStart"),
  startInTray: document.getElementById("startInTray"),
  checkUpdates: document.getElementById("checkUpdates"),
  allowMultiple: document.getElementById("allowMultiple"),
  currentVersionValue: document.getElementById("currentVersionValue"),
  checkVersionBtn: document.getElementById("checkVersionBtn"),
  updateStatusMessage: document.getElementById("updateStatusMessage"),
  toastContainer: document.getElementById("toastContainer"),
  settingsFolder: document.getElementById("settingsFolder"),
  appVersionLabel: document.getElementById("appVersionLabel"),
  navButtons: document.querySelectorAll(".nav-item"),
  tabPanels: document.querySelectorAll(".tab-panel"),
  toAddBtn: document.getElementById("toAddBtn"),
  importBtn: document.getElementById("importBtn"),
  clearTunnelBtn: document.getElementById("clearTunnelBtn"),
  clearLogsBtn: document.getElementById("clearLogsBtn"),
};
